# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_auto_20160913_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatturazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(blank=True, max_length=250, null=True, verbose_name='denominazione')),
                ('piva', models.CharField(blank=True, max_length=250, null=True, verbose_name='Piva')),
                ('codfisc', models.CharField(blank=True, max_length=250, null=True, verbose_name='codice fiscale')),
                ('indirizzo', models.CharField(blank=True, max_length=250, null=True, verbose_name='indirizzo')),
                ('cap', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cap')),
                ('citta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Citta')),
                ('nazione', models.CharField(blank=True, max_length=250, null=True, verbose_name='nazione')),
                ('telefono', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefono')),
                ('fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='Fax')),
                ('e_mail', models.CharField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('pec', models.CharField(blank=True, max_length=250, null=True, verbose_name='pec')),
                ('indirizzo_spedizione', models.BooleanField(default=False, verbose_name='\xe8 anche indirizzo di spedizione')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dati di Fatturazione',
            },
        ),
        migrations.CreateModel(
            name='IndirizzoSpedizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(blank=True, max_length=250, null=True, verbose_name='denominazione')),
                ('indirizzo', models.CharField(blank=True, max_length=250, null=True, verbose_name='indirizzo')),
                ('cap', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cap')),
                ('citta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Citta')),
                ('nazione', models.CharField(blank=True, max_length=250, null=True, verbose_name='nazione')),
                ('telefono', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefono')),
                ('fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='Fax')),
                ('e_mail', models.CharField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Indirizzo di Spedizione',
            },
        ),
    ]
