# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20161027_1350'),
        ('customer', '0005_auto_20161027_1304'),
    ]

    operations = [
    ]
