# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 15:09
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160829_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='thumb',
            field=image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='color',
            name='thumb',
            field=image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura'),
        ),
    ]
