# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 19:53
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_composition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiali'},
        ),
        migrations.AlterField(
            model_name='accessory',
            name='thumb',
            field=image_cropping.fields.ImageRatioField('image', '800x578', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='thumb',
            field=image_cropping.fields.ImageRatioField('image', '800x578', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=image_cropping.fields.ImageRatioField('image', '800x578', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura'),
        ),
    ]
