# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-02 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160727_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome colore')),
                ('image', models.ImageField(blank=True, null=True, upload_to='color', verbose_name='immagine colore')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name_plural': 'Forme',
            },
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='prompt_delivery',
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.ManyToManyField(blank=True, null=True, to='product.Shape', verbose_name='Seleziona Materiali'),
        ),
    ]
