# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_composition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='name',
        ),
    ]
