# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_composition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Titolo:'),
        ),
    ]
