# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20160907_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='cintureLunghezza',
            field=models.ForeignKey(blank=True, help_text='lascia vuoto se non e cintura', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.CintureLunghezza', verbose_name='Lunghezza Cinture'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='material',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Material', verbose_name='Metallo'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='maggiorazione di prezzo', max_digits=10, null=True, verbose_name='Prezzo'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='scarpemisura',
            field=models.ForeignKey(blank=True, help_text='lascia vuoto se non e scarpa', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.TagliaScarpe', verbose_name='Taglia Scarpe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, help_text='solo se a 40 giorni', null=True, to='product.Color', verbose_name='Seleziona Colori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='prezzo base', max_digits=10, null=True, verbose_name='Prezzo'),
        ),
    ]
