# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20160907_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='sconto percentuale'),
        ),
    ]
