# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20160907_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_fr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titolo Inglese'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titolo Inglese'),
        ),
        migrations.AddField(
            model_name='product',
            name='descrizione_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Francese'),
        ),
        migrations.AddField(
            model_name='product',
            name='descrizione_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Inglese'),
        ),
        migrations.AddField(
            model_name='product',
            name='end_season',
            field=models.DateField(blank=True, null=True, verbose_name='Fine Stagione'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titolo Inglese'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titolo Inglese'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_season',
            field=models.DateField(blank=True, null=True, verbose_name='Inizio Stagione'),
        ),
        migrations.AddField(
            model_name='product',
            name='summer',
            field=models.BooleanField(default=False, verbose_name='Estate'),
        ),
        migrations.AddField(
            model_name='product',
            name='winter',
            field=models.BooleanField(default=False, verbose_name='Winter'),
        ),
    ]
