# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20160913_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_fr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titolo Francese'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titolo Francese'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(editable=False, verbose_name='date published'),
        ),
    ]
