# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 19:38
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20160913_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='thumb',
            field=image_cropping.fields.ImageRatioField('image', '300x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura: 300x150px'),
        ),
    ]
