# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20160915_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='maggiorazione di prezzo', max_digits=10, null=True, verbose_name='Prezzo'),
        ),
    ]
