# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20160922_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profondita'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='altezza'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lenght',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='lunghezza'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='larghezza'),
        ),
    ]
