# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20160929_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_seller',
            field=models.BooleanField(default=False, verbose_name='Mostra in Piu Venduti'),
        ),
    ]
