# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_top_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name_plural': 'Colori'},
        ),
    ]
