# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20161007_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='name_fr',
            field=models.CharField(editable=False, max_length=100, null=True, verbose_name='Titolo Francese:'),
        ),
        migrations.AddField(
            model_name='composition',
            name='name_uk',
            field=models.CharField(editable=False, max_length=100, null=True, verbose_name='Titolo Inglese:'),
        ),
    ]
