# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20160929_1253'),
        ('product', '0023_auto_20161011_1029'),
        ('product', '0025_auto_20161011_1041'),
    ]

    operations = [
    ]
