"""
Django settings for djangocommerce project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c))rm1@rg@xux-+$h437e!c971gfyafbfofxa=@rihs*6@x13z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False

#ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'shop.bergeitalia.com', 'bergeitalia.com']
ALLOWED_HOSTS = []



# Application definition
INSTALLED_APPS = [
    rib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

GRAPPELLI_ADMIN_TITLE = "Berge Urban Couture"



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/var/www/bergebox/djangocommerce'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_ROOT = '/var/www/bergebox/djangocommerce/media/'

MEDIA_URL = "http://shop.bergeitalia.com/media/"



THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    #'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

from easy_thumbnails.conf import Settings as thumbnail_settings
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

    IMAGE_CROPPING_THUMB_SIZE = (1425, 500)
    #cropping = ImageRatioField('image', '1425x500', size_warning=True)
IMAGE_CROPPING_SIZE_WARNING = True




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.bergeitalia.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'shop@bergeitalia.com'
EMAIL_HOST_PASSWORD = 'palazzolesi52'
DEFAULT_FROM_EMAIL = 'shop@bergeitalia.com'
CONTACT_RECIPIENTS = False




#TINYMCE_JS_URL = os.path.join(MEDIA_ROOT, "/tiny_mce/tiny_mce.js")
#TINYMCE_JS_URL = 'http://http://127.0.0.1:8000/tinymce/tiny_mce/tiny_mce_src.js'
TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,spellchecker,paste,searchreplace",
    'theme': "advanced",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'height': "1000px",
    'width': "1040px",
}
#TINYMCE_SPELLCHECKER = True
#TINYMCE_COMPRESSOR = True
