# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titolo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('scritta', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('slider', image_cropping.fields.ImageRatioField('image', '1170x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Revolution Gallery')),
                ('slider_azienda', image_cropping.fields.ImageRatioField('image', '1170x431', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Slider Azienda')),
                ('thumb', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Miniatura')),
                ('croplibero', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Ritaglio Libero')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
