# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
    ]
