# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20160913_1456'),
        ('cart', '0002_auto_20160913_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cintureLunghezza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.CintureLunghezza', verbose_name='Lunghezza Cinture'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='scarpemisura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.TagliaScarpe', verbose_name='Misura scarpe'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Color', verbose_name='Colore'),
        ),
    ]
