# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20160913_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='codice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
