# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_reserved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo'),
        ),
    ]
