# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(blank=True, max_length=250, null=True, verbose_name='id utente')),
                ('name', models.CharField(max_length=100, verbose_name='Titolo:')),
                ('code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Codice')),
                ('tot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo')),
                ('tot_discount', models.IntegerField(blank=True, null=True, verbose_name='sconto percentuale')),
                ('price_reserved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo Scontato')),
                ('prompt_delivery', models.BooleanField(default=False, verbose_name='Pronta Consegna')),
                ('delivery', models.BooleanField(default=False, verbose_name='Consegna 40gg')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('confermato', models.BooleanField(default=False, verbose_name='confermato')),
                ('pagato', models.BooleanField(default=False, verbose_name='pagato')),
                ('spedito', models.BooleanField(default=False, verbose_name='spedito')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Ordine',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordine', models.CharField(blank=True, max_length=250, null=True, verbose_name='id ordine')),
                ('name', models.CharField(max_length=100, verbose_name='Titolo:')),
                ('code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Codice')),
                ('designer', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='sconto percentuale')),
                ('price_reserved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo Scontato')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Immagine')),
                ('croplibero', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Ritaglio Libero')),
                ('prompt_delivery', models.BooleanField(default=False, verbose_name='Pronta Consegna')),
                ('delivery', models.BooleanField(default=False, verbose_name='Consegna 40gg')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('album', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Prodotti Ordinati',
            },
        ),
    ]
