# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20160919_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tot_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Prezzo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Ordine'),
        ),
    ]
